SSAF-SOUND/ssaf-sound-be

src/main/java/com/ssafy/ssafsound/domain/lunch/domain/LunchPoll.java
src/main/java/com/ssafy/ssafsound/domain/member/domain/Member.java
src/main/java/com/ssafy/ssafsound/domain/post/domain/Post.java
src/main/java/com/ssafy/ssafsound/domain/recruit/domain/RecruitLimitation.java

- #12
- 데이터베이스 예약어와 중복된 네이밍으로 인한 오류 수정 및 컬럼 누락 수정
close #12

fix: 엔티티 클래스 멤버 변수 네이밍 수정 

---

src/main/java/com/ssafy/ssafsound/global/advice/ExceptionControllerAdvice.java
src/main/java/com/ssafy/ssafsound/global/common/exception/GlobalErrorInfo.java
src/main/java/com/ssafy/ssafsound/global/common/response/EnvelopeResponse.java

- 전역 예외처리용 ControllerAdvice 추가
- 컨트롤러 에러 수정과 리턴 형식 수정을 위해 EvelopeResponse 수정 -> 이제 컨트롤러에서 EnvelopeResponse 리턴할때 data 필드만 빌드하면됨.
- #16

 feat: 예외 처리

---

src/main/java/com/ssafy/ssafsound/domain/comment/domain/CommentLike.java

close SSAF-SOUND#24
- #24 
- 댓글 좋아요 엔티티 클래스 작성

feat: 댓글 좋아요 엔티티 클래스 작성

---

src/main/java/com/ssafy/ssafsound/domain/recruit/exception/RecruitErrorInfo.java
src/main/java/com/ssafy/ssafsound/domain/recruitcomment/controller/RecruitCommentController.java
src/main/java/com/ssafy/ssafsound/domain/recruitcomment/domain/RecruitComment.java
src/main/java/com/ssafy/ssafsound/domain/recruitcomment/dto/PatchRecruitCommentReqDto.java
src/main/java/com/ssafy/ssafsound/domain/recruitcomment/dto/PostRecruitCommentReqDto.java
src/main/java/com/ssafy/ssafsound/domain/recruitcomment/dto/PostRecruitCommentResDto.java
src/main/java/com/ssafy/ssafsound/domain/recruitcomment/repository/RecruitCommentRepository.java
src/main/java/com/ssafy/ssafsound/domain/recruitcomment/service/RecruitCommentService.java
src/main/java/com/ssafy/ssafsound/global/advice/ExceptionControllerAdvice.java
src/test/java/com/ssafy/ssafsound/domain/recruitcomment/service/RecruitCommentServiceTest.java

- #41 
- 세부 구현 사항 1
- 리크루팅 QNA 등록
- 리크루팅 QNA 수정
- 리크루팅 QNA 삭제
1. QNA 등록 시 추가적으로 고려해야되는 validation이 있다면 집중적으로 리뷰해서 알려주시면 보완하겠습니다. 
close #41

feat: 사용자 / 등록자 리크루팅 QNA CUD

---

src/main/java/com/ssafy/ssafsound/domain/auth/controller/AuthController.java
src/main/java/com/ssafy/ssafsound/domain/auth/service/oauth/OauthProviderFactory.java
src/main/java/com/ssafy/ssafsound/domain/auth/service/token/JwtTokenProvider.java
src/main/java/com/ssafy/ssafsound/domain/member/domain/Member.java
src/main/java/com/ssafy/ssafsound/domain/member/domain/OAuthType.java
src/main/java/com/ssafy/ssafsound/domain/member/dto/PostMemberReqDto.java
src/main/java/com/ssafy/ssafsound/domain/recruit/controller/RecruitController.java
src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitScrapRepository.java
src/main/java/com/ssafy/ssafsound/domain/recruit/service/RecruitService.java
src/main/java/com/ssafy/ssafsound/domain/recruitcomment/controller/RecruitCommentController.java
src/main/java/com/ssafy/ssafsound/domain/recruitcomment/domain/RecruitCommentLike.java
src/main/java/com/ssafy/ssafsound/domain/recruitcomment/repository/RecruitCommentLikeRepository.java
src/main/java/com/ssafy/ssafsound/domain/recruitcomment/service/RecruitCommentService.java
src/test/java/com/ssafy/ssafsound/domain/recruit/service/RecruitServiceTest.java
src/test/java/com/ssafy/ssafsound/domain/recruitcomment/service/RecruitCommentServiceTest.java

- #39 
- 세부 구현 사항 1
- 리크루팅 스크랩 구현
- 리크루팅 좋아요 기능 구현 
- Auth 객체 네이밍 수정으로 인한 변경사항 반영
- OAuthType 네이밍 수정으로 인한 변경사항 반영
Auth객체와 OAuthType으로 인해 다른 코드에 영향이 많이 가므로 각자 브랜치에서 빌드를 확인해주세요.

feat: 리크루팅 관련 좋아요 기능

---

.gitignore
build.gradle
src/main/java/com/ssafy/ssafsound/domain/meta/domain/MetaDataType.java
src/main/java/com/ssafy/ssafsound/domain/meta/domain/UploadDirectory.java
src/main/java/com/ssafy/ssafsound/domain/meta/service/EnumMetaDataConsumer.java
src/main/java/com/ssafy/ssafsound/global/advice/ExceptionControllerAdvice.java
src/main/java/com/ssafy/ssafsound/infra/config/S3Config.java
src/main/java/com/ssafy/ssafsound/infra/exception/InfraErrorInfo.java
src/main/java/com/ssafy/ssafsound/infra/exception/InfraException.java
src/main/java/com/ssafy/ssafsound/infra/storage/service/AwsS3StorageService.java
src/main/java/com/ssafy/ssafsound/infra/storage/service/StorageService.java
src/main/resources/application-local.yml

- #29
- Infra 패키지가 추가되었습니다.
- Infra 패키지 하위에 config, exception이 추가되었습니다.
- Infra 패키지 하위에 storage가 추가되었고, StorageService가 추가되어 이미지 업로드 및 삭제가 가능합니다.
- MetaData와 관련 클래스에 UploadDirectory 관련 사항이 추가 변경되었습니다.
- resources에 yml 설정이 추가되었습니다.
- build.gradle에 aws 관련 사항이 추가되었습니다.
- CloudFront가 적용되었습니다.
- 서비스 주입
```java
private final StorageService storageService;
```
- 이미지 업로드
```java
private final MetaDataConsumer metaDataConsumer;
public void save(MultipartFile multipartFile, AuthenticatedMember member) {
MetaData uploadDir = metaDataConsumer.getMetaData("UPLOAD_DIRECTORY","post");
storageService.putObject(multipartFile, uploadDir, member.getMemberId())
}
```
- 이미지 삭제
```java
storageService.deleteObject(filename);
```
- 여러 이미지를 한 번에 올려야할 때, 정합성을 위해서 예외 발생 시 업로드에 성공한 이미지는 바로 삭제해주세요.
close #29

feat: S3 스토리지 연결 #29

---

src/main/java/com/ssafy/ssafsound/domain/lunch/dto/GetLunchListReqDto.java

- yyyyMMdd -> yyyy-MM-dd 형식으로 변경
- #34 
yyyyMMdd 형식에서 -> yyyy-MM-dd 형식으로 변경
close #34

fix: 점심 조회 API 날짜 포맷 변경

---

src/main/java/com/ssafy/ssafsound/domain/board/exception/BoardErrorInfo.java
src/main/java/com/ssafy/ssafsound/domain/board/exception/BoardException.java
src/main/java/com/ssafy/ssafsound/domain/post/controller/PostController.java
src/main/java/com/ssafy/ssafsound/domain/post/domain/Post.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostListResDto.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostResDto.java
src/main/java/com/ssafy/ssafsound/domain/post/exception/PostErrorInfo.java
src/main/java/com/ssafy/ssafsound/domain/post/exception/PostException.java
src/main/java/com/ssafy/ssafsound/domain/post/repository/PostRepository.java
src/main/java/com/ssafy/ssafsound/domain/post/service/PostService.java
src/main/java/com/ssafy/ssafsound/global/advice/ExceptionControllerAdvice.java
src/main/resources/application-local.yml
src/main/resources/application.yml

- #46 
- 게시판 목록 조회 기능 구현
- 페이지네이션 적용
- 게시판 관련 예외 처리 구현
- Post 엔티티 Comment 연관 관계 추가
N+1 문제가 발생할 가능성이 있습니다. 이 부분은 추후에 새로운 이슈 사항으로 반영하겠습니다.
단순 조회 기능은 목업 데이터를 넣는데 어려움이 있어서 테스트 코드는 새로운 이슈 사항으로 작성하겠습니다.

feat: 게시글 목록 조회 기능 구현

---

src/main/java/com/ssafy/ssafsound/domain/recruit/domain/RecruitLimitation.java
src/main/java/com/ssafy/ssafsound/domain/recruit/exception/RecruitErrorInfo.java
src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitQuestionReplyRepository.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/controller/RecruitApplicationController.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/domain/MatchStatus.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/domain/RecruitApplication.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/PostRecruitApplicationReqDto.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/repository/RecruitApplicationRepository.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/service/RecruitApplicationService.java
src/test/java/com/ssafy/ssafsound/domain/recruitapplication/service/RecruitApplicationServiceTest.java

- #63 
1. 리크루트 취소 기능 추가
2. 리크루트 신청 프로필 공개여부 column 삭제
3. 리크루트 신청 관련 테스트 코드 작성 및 버그 수정

fix: 리크루트 신청 로직 수정

---

src/main/java/com/ssafy/ssafsound/domain/post/controller/PostController.java
src/main/java/com/ssafy/ssafsound/domain/post/repository/PostScrapRepository.java
src/main/java/com/ssafy/ssafsound/domain/post/service/PostService.java

feat: 게시글 스크랩 기능 구현

---

src/main/java/com/ssafy/ssafsound/domain/post/controller/PostController.java
src/main/java/com/ssafy/ssafsound/domain/post/service/PostService.java

fix: 코드 중복 및 코드누락 수정

---

src/main/java/com/ssafy/ssafsound/batch/tasklet/PostTasklet.java
src/main/java/com/ssafy/ssafsound/domain/post/controller/PostController.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetHotPost.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetHotPostElement.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetHotPostResDto.java
src/main/java/com/ssafy/ssafsound/domain/post/exception/PostErrorInfo.java
src/main/java/com/ssafy/ssafsound/domain/post/repository/HotPostRepository.java
src/main/java/com/ssafy/ssafsound/domain/post/service/PostService.java

- #96 
- 핫 게시글 목록 조회 기능 구현
- 게시글 목록이 없을 때 예외 처리

feat: 핫 게시글 목록 조회 기능 구현

---

src/main/java/com/ssafy/ssafsound/domain/board/exception/BoardErrorInfo.java
src/main/java/com/ssafy/ssafsound/domain/board/service/BoardService.java
src/main/java/com/ssafy/ssafsound/domain/post/controller/PostController.java
src/main/java/com/ssafy/ssafsound/domain/post/domain/Post.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostHotElement.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostHotResDto.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostMyElement.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostMyResDto.java
src/main/java/com/ssafy/ssafsound/domain/post/exception/PostErrorInfo.java
src/main/java/com/ssafy/ssafsound/domain/post/repository/HotPostRepository.java
src/main/java/com/ssafy/ssafsound/domain/post/repository/PostRepository.java
src/main/java/com/ssafy/ssafsound/domain/post/service/PostService.java

- #97 
- 나의 게시글 목록 조회 기능 구현
- post, hotpost 단방향 관계로 수정(연쇄 삭제 직접 구현)
- 자신의 게시글은 신고 못하도록 수정
- 빈 게시판 예외 삭제
- 일부 dto 네이밍 수정

feat: 나의 게시글 목록 조회 기능 구현

---

src/main/java/com/ssafy/ssafsound/domain/member/controller/MemberController.java
src/main/java/com/ssafy/ssafsound/domain/member/domain/Member.java
src/main/java/com/ssafy/ssafsound/domain/member/dto/PostCertificationInfoReqDto.java
src/main/java/com/ssafy/ssafsound/domain/member/dto/PostCertificationInfoResDto.java
src/main/java/com/ssafy/ssafsound/domain/member/exception/MemberErrorInfo.java
src/main/java/com/ssafy/ssafsound/domain/member/service/MemberService.java
src/main/java/com/ssafy/ssafsound/domain/meta/domain/Certification.java
src/main/java/com/ssafy/ssafsound/domain/meta/domain/MetaDataType.java
src/main/java/com/ssafy/ssafsound/domain/meta/service/EnumMetaDataConsumer.java
src/test/java/com/ssafy/ssafsound/domain/member/service/MemberServiceTest.java

- #108 
- 싸피생 인증 관련 정답을 MetaData로 제공합니다.
- 발생할 수 있는 케이스들에 대해 테스트 코드를 추가했습니다.
- JUnit 5의 @ParameterizedTest를 활용했습니다. [공식문서 참고](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-argument-aggregation)
- 전공 트랙에 대한 기획 확정이 나지 않아서, Draft pull Request로 올립니다.
- 확정 시, 전공 트랙에 대한 Entity는 Enum으로 변경할 예정

feat: 싸피생 인증 추가

---

src/main/java/com/ssafy/ssafsound/domain/auth/validator/AuthenticationArgumentResolver.java
src/main/java/com/ssafy/ssafsound/domain/recruit/controller/RecruitController.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/GetRecruitDetailResDto.java
src/main/java/com/ssafy/ssafsound/domain/recruit/service/RecruitService.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/controller/RecruitApplicationController.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/RecruitParticipantElement.java
src/main/java/com/ssafy/ssafsound/domain/recruitcomment/controller/RecruitCommentController.java
src/test/java/com/ssafy/ssafsound/domain/recruitapplication/service/RecruitApplicationServiceTest.java

- #87 
- #100 
- #116
- SSAFY info 수정에 따른 Response Body 변경 사항 적용

fix : SSAFY Info 수정에 따른 Response Body 데이터 변경

---

src/main/java/com/ssafy/ssafsound/domain/comment/controller/CommentController.java
src/main/java/com/ssafy/ssafsound/domain/comment/dto/PostCommentWriteReplyReqDto.java
src/main/java/com/ssafy/ssafsound/domain/comment/exception/CommentErrorInfo.java
src/main/java/com/ssafy/ssafsound/domain/comment/service/CommentService.java

- #93 
- 대댓글 작성 기능 구현
댓글 작성과 전체적인 로직은 동일하지만, commentGroup에 부모 댓글을 담고, 예외가 추가되었다는 차이가 있습니다.

feat: 대댓글 작성 기능 구현

---

src/main/java/com/ssafy/ssafsound/domain/meta/domain/Skill.java
src/main/java/com/ssafy/ssafsound/domain/meta/service/EnumMetaDataConsumer.java

- #130
- 세부 구현 사항 
1. 메타데이터 대소문자 lower case로 변경 해서 조회되도록 수정
2. Skill 메타 데이터 추가

refactor: 메타데이터 조회 시 대소문자 구별 없도록 변경

---

src/main/java/com/ssafy/ssafsound/domain/comment/controller/CommentController.java
src/main/java/com/ssafy/ssafsound/domain/comment/domain/Comment.java
src/main/java/com/ssafy/ssafsound/domain/comment/service/CommentService.java

feat: 댓글 삭제 기능 구현

---

src/main/java/com/ssafy/ssafsound/domain/BaseTimeEntity.java
src/main/java/com/ssafy/ssafsound/domain/comment/controller/CommentController.java
src/main/java/com/ssafy/ssafsound/domain/comment/domain/Comment.java
src/main/java/com/ssafy/ssafsound/domain/comment/repository/CommentLikeRepository.java
src/main/java/com/ssafy/ssafsound/domain/comment/service/CommentService.java

- #121 
-  댓글 좋아요 기능 구현
BaseTimeEntity의 modifiedAt 필드에 최초 저장 시 null이 저장되도록 다음과 같은 어노테이션을 추가했습니다.
```
@Column(insertable = false)
```

feat: 댓글 좋아요 기능 구현

---

src/main/java/com/ssafy/ssafsound/domain/comment/domain/Comment.java
src/main/java/com/ssafy/ssafsound/domain/comment/service/CommentService.java

fix: 충돌 해결로 인한 오탈자 수정

---

src/main/java/com/ssafy/ssafsound/domain/recruit/controller/RecruitController.java
src/main/java/com/ssafy/ssafsound/domain/recruit/domain/Recruit.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/GetRecruitDetailResDto.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/RecruitElement.java
src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitDynamicQueryRepository.java
src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitRepository.java
src/main/java/com/ssafy/ssafsound/domain/recruit/service/RecruitService.java
src/main/java/com/ssafy/ssafsound/domain/recruit/task/RecruitCron.java
src/test/java/com/ssafy/ssafsound/domain/recruit/service/RecruitServiceTest.java

- #135
- 세부 구현 사항 1
- 리크루트 인원이 가득찬 경우에도, 모집 인원을 수정해서 추가하는 경우 추가모집을 할 수 있어야하므로,  기존 메서드를 컬럼으로 변경.
- 만료 조건은 글 등록자가 직접 만료시키거나 모집일이 완료된 경우에 수정됨.

feat: 리크루트 완료 기능 추가 

---

src/main/java/com/ssafy/ssafsound/domain/member/controller/MemberController.java
src/main/java/com/ssafy/ssafsound/domain/member/domain/Member.java
src/main/java/com/ssafy/ssafsound/domain/member/domain/MemberProfile.java
src/main/java/com/ssafy/ssafsound/domain/member/dto/GetMemberPortfolioResDto.java
src/main/java/com/ssafy/ssafsound/domain/member/dto/PutMemberProfileReqDto.java
src/main/java/com/ssafy/ssafsound/domain/member/repository/MemberRepository.java
src/main/java/com/ssafy/ssafsound/domain/member/service/MemberService.java
src/main/java/com/ssafy/ssafsound/global/interceptor/AuthInterceptor.java

- #145 
- 멤버는 자기 소개, 소개 링크, 소개 기술 스택을 조회할 수 있습니다.
- 멤버의 자기소개가 비어있거나, 소개 링크가 비어있거나, 기술 스택이 비어있을 수 있습니다.
- 해당 조회 쿼리를 위해 inner join을 사용하는 fetch join으로 쿼리를 작성했으나, 비어있을 수 있는 내용 때문에 방법을 EntityGraph로 변경하여 적용하였습니다.
```Text
Hibernate: 
select
member0_.member_id as member_i1_9_0_,
memberskil1_.member_skill_id as member_s1_16_1_,
memberlink2_.member_link_id as member_l1_12_2_,
member0_.created_at as created_2_9_0_,
member0_.modified_at as modified3_9_0_,
member0_.account_state as account_4_9_0_,
member0_.campus as campus5_9_0_,
member0_.certification_inquiry_count as certific6_9_0_,
member0_.certification_state as certific7_9_0_,
member0_.certification_try_time as certific8_9_0_,
member0_.major as major9_9_0_,
member0_.major_track as major_t10_9_0_,
member0_.nickname as nicknam11_9_0_, …
```

feat: member get portfolio

---

src/main/java/com/ssafy/ssafsound/domain/member/controller/MemberController.java
src/main/java/com/ssafy/ssafsound/domain/member/domain/Member.java
src/main/java/com/ssafy/ssafsound/domain/member/dto/GetMemberPortfolioResDto.java
src/main/java/com/ssafy/ssafsound/domain/member/dto/GetMemberProfileResDto.java
src/main/java/com/ssafy/ssafsound/domain/member/dto/PortfolioElement.java
src/main/java/com/ssafy/ssafsound/domain/member/service/MemberService.java

- #132 
- 포트폴리오가 아닌 멤버의 프로필인 경우, 권한 상관 없이 조회될 수 있어야 합니다.
***그림 참고***
닉네임, 싸피멤버 여부, 전공자, 싸피 정보에 따른 데이터들을 통해 해당 프로필을 만들 수 있습니다.
* 리팩토링 ISSUE -> return null 은 상당히 부자연스러워 보입니다.
```Java
if (member.getPublicPortfolio()) {
MemberProfile memberProfile = memberProfileRepository.findMemberProfileByMember(member)
.orElseGet(MemberProfile::new);
return GetMemberPortfolioResDto.of(member, memberProfile);
}
return null;
}
```
멤버의 포트폴리오 공개 여부가 **공개**로 되어 있다면 기존의 response에서는
```Java
{
"code": "200",
"message": "success",
"data": {
"selfIntroduction": "안녕하세요",
"skills": [
"Vue",
"Spring",
"Java",
"React"
],
"memberLinks": [
{
"linkName": "velog",
"path": "https://velog.io/"
},
{
"linkName": "github",
"path": "https://github.com/YongsHub"
}
]
}
}
```
와 같은 데이터가 제공 되고, 비공개였다면
```Java
{
"code": "200", …
```

feat: 멤버 프로필 조회 및 포트폴리오 공개 여부에 따른 로직 리팩토링

---

src/main/java/com/ssafy/ssafsound/infra/storage/StorageController.java
src/main/java/com/ssafy/ssafsound/infra/storage/dto/ImagePathDto.java
src/main/java/com/ssafy/ssafsound/infra/storage/dto/PostStoreImageResDto.java
src/main/java/com/ssafy/ssafsound/infra/storage/service/AwsS3PreSignerService.java
src/main/java/com/ssafy/ssafsound/infra/storage/service/AwsS3PresignerService.java

refactor: presigned url upload 도입

---

src/main/java/com/ssafy/ssafsound/domain/comment/controller/CommentController.java
src/main/java/com/ssafy/ssafsound/domain/comment/domain/Comment.java
src/main/java/com/ssafy/ssafsound/domain/comment/dto/GetCommentElement.java
src/main/java/com/ssafy/ssafsound/domain/comment/dto/GetCommentResDto.java
src/main/java/com/ssafy/ssafsound/domain/comment/repository/CommentRepository.java
src/main/java/com/ssafy/ssafsound/domain/comment/service/CommentService.java

- #150 
- 댓글, 대댓글 구조화
- ssafyInfo 관련 정보 응답 데이터 추가
- 페이지네이션 삭제
- soft delete 포함하기(삭제되었는지 deleteComment 응답 데이터 추가)

refactor: 댓글 관련 리팩토링

---

src/main/java/com/ssafy/ssafsound/domain/recruit/controller/RecruitController.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/GetRecruitDetailResDto.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/GetRecruitLimitDetail.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/Participant.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/PostRecruitScrapCountResDto.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/RecruitElement.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/RecruitParticipant.java
src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitScrapRepository.java
src/main/java/com/ssafy/ssafsound/domain/recruit/service/RecruitService.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/ParticipantElement.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/RecruitApplicationElement.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/RecruitParticipantElement.java
src/main/java/com/ssafy/ssafsound/domain/recruitcomment/dto/PostRecruitCommentResDto.java
src/main/java/com/ssafy/ssafsound/domain/recruitcomment/dto/RecruitCommentElement.java
src/test/java/com/ssafy/ssafsound/domain/recruit/service/RecruitServiceTest.java
src/test/java/com/ssafy/ssafsound/domain/recruitapplication/service/RecruitApplicationServiceTest.java
src/test/java/com/ssafy/ssafsound/domain/recruitcomment/service/RecruitCommentServiceTest.java

- #164 
- 세부 구현 사항
1. 리크루트 단건조회에서 전체 스크랩 숫자 추가
2. 리크루트 스크랩 시, 스크랩 숫자 Return 하도록 변경
3. 기타 네이밍 오류 수정

refactor: 리크루트 스크랩 리팩토링

---

src/main/java/com/ssafy/ssafsound/domain/recruit/domain/Recruit.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/GetRecruitDetailResDto.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/PatchRecruitReqDto.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/PostRecruitReqDto.java
src/test/java/com/ssafy/ssafsound/domain/recruit/dto/PostRecruitReqDtoTest.java
src/test/java/com/ssafy/ssafsound/domain/recruit/service/RecruitServiceTest.java

- #176
1. 리크루트 등록시 등록자와 연락할 수 있는 오픈카카오톡 or discord등의 url정보 필요
2. recruit table에 contactURL column 추가 및 등록, 조회 시 columm 정보 추가

feat: 리크루트 contactURI 컬럼 추가

---

src/main/java/com/ssafy/ssafsound/domain/lunch/service/LunchPollService.java
src/test/java/com/ssafy/ssafsound/domain/lunch/service/LunchPollServiceTest.java

fix : Lunch 테스트 실패 수정

---

src/test/java/com/ssafy/ssafsound/domain/lunch/service/LunchServiceTest.java

- LunchPoll의 lunch를 그냥 빌더로 set하던 것을 직접 정의한 연관관계 편의메소드 set으로 설정하도록 수정
- 120 width 넘어가는 코드 개행

feat : LunchServiceTest 수정

---

src/main/java/com/ssafy/ssafsound/domain/board/domain/Board.java
src/main/java/com/ssafy/ssafsound/domain/board/dto/GetBoardElement.java
src/main/java/com/ssafy/ssafsound/domain/chat/dto/ChatRoomElementDto.java
src/main/java/com/ssafy/ssafsound/domain/comment/domain/Comment.java
src/main/java/com/ssafy/ssafsound/domain/comment/dto/AuthorElement.java
src/main/java/com/ssafy/ssafsound/domain/comment/dto/GetCommentElement.java
src/main/java/com/ssafy/ssafsound/domain/comment/dto/PostCommentWriteReplyReqDto.java
src/main/java/com/ssafy/ssafsound/domain/comment/dto/PostCommentWriteReqDto.java
src/main/java/com/ssafy/ssafsound/domain/comment/dto/PutCommentUpdateReqDto.java
src/main/java/com/ssafy/ssafsound/domain/comment/service/CommentService.java
src/main/java/com/ssafy/ssafsound/domain/post/controller/PostController.java
src/main/java/com/ssafy/ssafsound/domain/post/domain/Post.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/AuthorElement.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostDetailElement.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostDetailResDto.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostElement.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostHotElement.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostHotResDto.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostMyElement.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostMyResDto.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostResDto.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/PostPostLikeResDto.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/PostPostScrapResDto.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/PostPostWriteReqDto.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/PostPutUpdateReqDto.java
src/main/java/com/ssafy/ssafsound/domain/post/repository/PostLikeRepository.java
src/main/java/com/ssafy/ssafsound/domain/post/repository/PostRepository.java
src/main/java/com/ssafy/ssafsound/domain/post/repository/PostScrapRepository.java
src/main/java/com/ssafy/ssafsound/domain/post/service/PostService.java
src/main/java/com/ssafy/ssafsound/infra/storage/service/AwsS3StorageService.java

- #183 
- 게시판 목록
- imageUrl, description 필드 추가
- usedBoard 필드 삭제
- 게시글 목록 & 게시글 검색 & 핫 게시글 목록 & 핫 게시글 검색 & 나의 게시글 목록
- postId 필드 추가
- boardId 필드 추가
- createAt -> createdAt
- 게시글 상세보기 & 댓글
- author에 member정보 구조화(nickname 포함)
- 게시판 정보 추가(boardId, boardTitle)
- postId 필드 추가
- 익명 작성자일 때 member정보 nickname만 포함
- MemberRole타입 String으로 수정(버그 수정)
- 게시글 좋아요 & 게시글 스크랩
- 현재 좋아요 & 스크랩 상태 필드 추가
- 현재 좋아요 & 스크랩 개수 필드 추가
- 게시글 삭제
- imagePath 삭제 및 s3 이미지 삭제 로직 추가
- 댓글
- commentId 추가
- 삭제된 댓글이면 content 빈 문자열로 수정
- anonymous -> anonymity로 수정

fix: 익명 게시판 요청 & 응답 데이터 수정

---

src/docs/asciidoc/index.adoc
src/docs/asciidoc/metadata.adoc
src/test/java/com/ssafy/ssafsound/domain/meta/controller/MetaDataControllerTest.java
src/test/java/com/ssafy/ssafsound/utils/BaseRestDocControllerTest.java

- #185 
- 메타데이터 테스트 코드 추가
- 컨트롤러 테스트 공통부분 클래스로 추가

test: 메타데이터 컨트롤러 테스트 추가 

---

src/test/java/com/ssafy/ssafsound/utils/BaseRestDocControllerTest.java

test: 로그인 모킹을 위한 access-token 생성 로직 추가 

---

.github/workflows/dev-CI.yml
.github/workflows/dev-CICD.yml
appspec.yml
build.gradle
scripts/deploy.sh
src/main/java/com/ssafy/ssafsound/domain/comment/domain/Comment.java
src/main/java/com/ssafy/ssafsound/domain/member/dto/GetMemberDefaultInfoResDto.java
src/main/java/com/ssafy/ssafsound/health/controller/HealthController.java

- AWS의 포트포워딩을 위해서 ALB를 사용하려면 health check가 가능해야합니다. 따라서 HealthController를 추가했습니다.
- 이외에 cicd 스크립트를 추가했습니다.(data.sql 포함하도록)
-

[INFRA] dev 브랜치 cicd 설정 추가

---

build.gradle
src/docs/asciidoc/index.adoc
src/docs/asciidoc/lunch.adoc
src/main/java/com/ssafy/ssafsound/domain/lunch/controller/LunchController.java
src/main/java/com/ssafy/ssafsound/domain/lunch/repository/LunchRepository.java
src/main/resources/static/docs/index.html
src/test/java/com/ssafy/ssafsound/domain/lunch/controller/LunchControllerTest.java
src/test/java/com/ssafy/ssafsound/global/docs/ControllerTest.java
src/test/java/com/ssafy/ssafsound/global/docs/snippet/CookieDescriptionSnippet.java
src/test/java/com/ssafy/ssafsound/global/util/fixture/LunchFixture.java
src/test/resources/org/springframework/restdocs/templates/asciidoctor/cookie.snippet

- #190 
- Cookie의 accessToken의 경우 옵션, 필수, 불필요 등 경우에 따라서 명시해주어야한다고 생각했습니다. 그러나 Cookie의 description을 붙이는 기능은 Rest Docs와 관련 라이브러리에 아직 추가되지 않은 것을 확인했습니다. 이에 따라 `CookieDescriptionSnippet` 클래스와 `.snippet` 파일을 만들었고 이를 사용했습니다.
- 패키지는 src.test.java.com.ssafy.ssafsound.global.docs.snippet 입니다.
- 해당 클래스는 src.test.resources.org.springframework.restdocs.templates.asciidoctor.cookie.snippet 이라는 mustache 문법의 snippet 파일을 이용해 cookie.adoc 파일을 만들게 됩니다.
- 해당 쿠키 스니펫을 docs에 포함 시키고 싶다면 다음 두 가지를 추가하면 됩니다.
1. 스니펫 파라미터 추가
```java
restDocs.cookie(ACCESS_TOKEN)
.when().post("/lunch/poll/{lunchId}", 2L)
.then().log().all()
.assertThat()
.statusCode(HttpStatus.OK.value())
.apply(document("lunch/poll",
requestCookieAccessTokenMandatory(),
pathParameters(
parameterWithName("lunchId").description("점심 메뉴 아이디")
), …
```

[TEST][DOCS] LunchController Rest Docs & Test 추가 + CookieDescriptionSnippet 추가

---

src/docs/asciidoc/index.adoc
src/docs/asciidoc/member.adoc
src/main/java/com/ssafy/ssafsound/domain/auth/dto/CreateMemberReqDto.java
src/main/java/com/ssafy/ssafsound/domain/member/controller/MemberController.java
src/main/java/com/ssafy/ssafsound/domain/member/domain/MemberProfile.java
src/main/java/com/ssafy/ssafsound/domain/member/dto/GetMemberPortfolioResDto.java
src/main/java/com/ssafy/ssafsound/domain/member/dto/PostMemberInfoReqDto.java
src/main/java/com/ssafy/ssafsound/domain/member/dto/PostNicknameReqDto.java
src/main/java/com/ssafy/ssafsound/domain/member/exception/MemberErrorInfo.java
src/main/java/com/ssafy/ssafsound/domain/member/service/MemberService.java
src/test/java/com/ssafy/ssafsound/domain/member/controller/MemberControllerTest.java
src/test/java/com/ssafy/ssafsound/global/util/fixture/MemberFixture.java

- #211 
- member domain rest docs
-
-

test: member domain rest docs with Rest Assured

---

src/docs/asciidoc/recruitApplication.adoc
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/PatchRecruitApplicationStatusResDto.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/PostRecruitScrapCountResDto.java
src/main/java/com/ssafy/ssafsound/domain/recruit/service/RecruitService.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/controller/RecruitApplicationController.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/service/RecruitApplicationService.java
src/main/java/com/ssafy/ssafsound/domain/recruitcomment/controller/RecruitCommentController.java
src/main/java/com/ssafy/ssafsound/domain/recruitcomment/dto/GetRecruitCommentsResDto.java
src/main/java/com/ssafy/ssafsound/domain/recruitcomment/dto/PostRecruitApplicationLikeResDto.java
src/main/java/com/ssafy/ssafsound/domain/recruitcomment/dto/PostRecruitCommentLikeResDto.java
src/main/java/com/ssafy/ssafsound/domain/recruitcomment/dto/PostRecruitCommentResDto.java
src/main/java/com/ssafy/ssafsound/domain/recruitcomment/dto/RecruitCommentElement.java
src/main/java/com/ssafy/ssafsound/domain/recruitcomment/repository/RecruitCommentLikeRepository.java
src/main/java/com/ssafy/ssafsound/domain/recruitcomment/service/RecruitCommentService.java
src/test/java/com/ssafy/ssafsound/domain/recruit/controller/RecruitControllerTest.java
src/test/java/com/ssafy/ssafsound/domain/recruitapplication/controller/RecruitApplicationControllerTest.java
src/test/java/com/ssafy/ssafsound/domain/recruitcomment/controller/RecruitCommentControllerTest.java
src/test/java/com/ssafy/ssafsound/domain/recruitcomment/service/RecruitCommentServiceTest.java
src/test/java/com/ssafy/ssafsound/global/util/fixture/RecruitApplicationFixture.java
src/test/java/com/ssafy/ssafsound/global/util/fixture/RecruitCommentFixture.java
src/test/java/com/ssafy/ssafsound/global/util/fixture/RecruitFixture.java

refactor: recruit update api response

---

src/docs/asciidoc/recruit.adoc
src/docs/asciidoc/recruitComment.adoc
src/main/resources/static/docs/index.html

docs: recruit ascii docs

---

.github/workflows/dev-CI.yml
.github/workflows/dev-CICD.yml
scripts/deploy.sh
src/test/java/com/ssafy/ssafsound/SsafsoundApplicationTests.java

- pr 시엔 테스트만 하도록 수정
- 프로퍼티 파일 통합
- PR 시엔 테스트만 하도록, Push 시엔 빌드와 배포를 하도록 변경했습니다.
- 빌드 과정에서 yml 파일을 모두 통합시킨 application-dev.yml로 빌드하도록 변경했습니다.

fix : cicd 스크립트 수정

---

src/main/java/com/ssafy/ssafsound/domain/recruit/exception/RecruitErrorInfo.java

fix: 리크루트 에러 문구 오탈자 수정

---

src/main/java/com/ssafy/ssafsound/domain/recruit/dto/GetRecruitDetailResDto.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/controller/RecruitApplicationController.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/GetRecruitApplicationDetailResDto.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/GetRecruitApplicationsResDto.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/RecruitApplicationElement.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/service/RecruitApplicationService.java
src/main/resources/static/docs/index.html
src/test/java/com/ssafy/ssafsound/domain/recruit/controller/RecruitControllerTest.java
src/test/java/com/ssafy/ssafsound/domain/recruit/service/RecruitServiceTest.java
src/test/java/com/ssafy/ssafsound/domain/recruitapplication/controller/RecruitApplicationControllerTest.java
src/test/java/com/ssafy/ssafsound/global/util/fixture/RecruitApplicationFixture.java
src/test/java/com/ssafy/ssafsound/global/util/fixture/RecruitFixture.java

- #233 
- 필드명 수정 isLike -> liked
- 리크루트 조회시 카테고리 정보 추가 
- 데이터 조회 시 recruitId, recruitStatus 데이터 중복을 피하기 위한 json property access level 설정 
- 등록자 참여신청 조회시 recruitType를 key로하는 map 형태로 데이터 구조화 (기존 List형태) (프론트엔드 요청사항 반영)

refactor: 리크루트 참여 단건 조회, 등록자 리쿠르트 신청자 조회 데이터 구조화 반영

---

src/main/java/com/ssafy/ssafsound/domain/lunch/domain/Lunch.java
src/main/java/com/ssafy/ssafsound/domain/lunch/domain/LunchPoll.java
src/main/java/com/ssafy/ssafsound/domain/lunch/dto/GetLunchListElementResDto.java
src/main/java/com/ssafy/ssafsound/domain/lunch/dto/GetLunchListResDto.java
src/main/java/com/ssafy/ssafsound/domain/lunch/dto/PostLunchPollResDto.java
src/main/java/com/ssafy/ssafsound/domain/lunch/exception/LunchErrorInfo.java
src/main/java/com/ssafy/ssafsound/domain/lunch/service/LunchPollService.java
src/main/java/com/ssafy/ssafsound/domain/lunch/service/LunchService.java
src/test/java/com/ssafy/ssafsound/domain/lunch/service/LunchServiceTest.java
src/test/java/com/ssafy/ssafsound/global/util/fixture/LunchFixture.java

- #
- 잘못된 일자나 데이터가 없는 점심 조회 쿼리에 대해 예외 처리하지 않고 빈 배열을 응답하도록 변경 
- Lunch 엔티티에 pollCount 컬럼을 추가하여 count 쿼리 대신 해당 필드를 읽도록 변경.

refactor : 점심 조회 로직 수정, 점심 투표수 컬럼 추가에 따른 리팩토링

---

src/docs/asciidoc/recruit.adoc
src/docs/asciidoc/recruitApplication.adoc
src/main/resources/static/docs/index.html

- 세부 구현 사항 1
- 사용자 스크랩한 리크루트 조회,
- 사용자 신청한 리크루트 조회,
- 사용자 참여중 리크루트 조회,
- 사용자 참여대기중 리크루트 신청 조회,
- 등록자 거절한 리크루트 목록 조회 
- api 문서 일괄 추가

docs: 리크루트 문서작업 일괄 추가 

---

src/main/java/com/ssafy/ssafsound/domain/recruit/controller/RecruitController.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/GetRejectedRecruitApplicationsResDto.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/PostRecruitResDto.java
src/main/java/com/ssafy/ssafsound/domain/recruit/service/RecruitService.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/controller/RecruitApplicationController.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/GetRecruitApplicationsResDto.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/RecruitApplicationResElement.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/service/RecruitApplicationService.java
src/main/resources/static/docs/index.html
src/test/java/com/ssafy/ssafsound/domain/post/service/PostServiceTest.java
src/test/java/com/ssafy/ssafsound/domain/recruit/controller/RecruitControllerTest.java
src/test/java/com/ssafy/ssafsound/domain/recruit/service/RecruitServiceTest.java
src/test/java/com/ssafy/ssafsound/domain/recruitapplication/controller/RecruitApplicationControllerTest.java
src/test/java/com/ssafy/ssafsound/global/util/fixture/MemberFixture.java
src/test/java/com/ssafy/ssafsound/global/util/fixture/RecruitApplicationFixture.java
src/test/java/com/ssafy/ssafsound/global/util/fixture/RecruitFixture.java

fix: reject recruit-application

---

src/main/java/com/ssafy/ssafsound/domain/lunch/task/LunchScraper.java

- THU -> TUE 로 변경
- 목요일에 스크랩 안하던 현상 해결

fix : cron 요일 수정

---

src/main/java/com/ssafy/ssafsound/domain/post/controller/PostController.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostHotReqDto.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostMyReqDto.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostSearchReqDto.java

- #264 
- 페이지네이션 cursor 버그 수정
- PostController에 ModelAttribute 명시
이전 pr에 cursor의 기본값을 추가했지만 모두 다 적용되지 않았기 때문에
모든 dto의 cursor의 기본값을 -1로 하도록 수정했습니다.

fix: 페이지네이션 cursor 버그 수정

---

src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitDynamicQueryRepositoryImpl.java

- #272
- 리크루트 목록 조회 시 모집 종료 조건 누락으로 인해, 모집중 필터링이 동작하지 않는 오류 수정

fix: 리크루트 목록 조회 모집종료 조건 누락 수정

---

build.gradle
src/test/java/com/ssafy/ssafsound/domain/term/controller/TermControllerTest.java
src/test/java/com/ssafy/ssafsound/domain/term/service/TermServiceTest.java
src/test/java/com/ssafy/ssafsound/global/util/fixture/TermFixture.java

- #275 
- JaCoCo Test Coverage 목표치 달성을 위해 TermService Test Code를 추가했습니다.
- gradle에서 Coverage 측정에서 제외시켰던  TermService를 포함했습니다.
-

test: TermService test code 추가

---

src/main/java/com/ssafy/ssafsound/domain/recruit/controller/RecruitController.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/GetMemberAppliedRecruitOffsetReqDto.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/GetMemberJoinOffsetRecruitReqDto.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/GetRecruitsOffsetReqDto.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/RecruitOffsetPagingRequestDto.java
src/main/java/com/ssafy/ssafsound/domain/recruit/service/RecruitService.java

- #283
- 세부 구현 사항 1
-리크루트 offset관련, default value적용을 위한 클래스 추가 
-

fix: 리크루트 offset기반 페이징 클래스 추가 및 일괄 적용 

---

src/main/java/com/ssafy/ssafsound/domain/auth/controller/AuthController.java
src/main/resources/static/docs/index.html
src/test/java/com/ssafy/ssafsound/domain/auth/controller/AuthControllerTest.java

- #291 
- 토큰 재발급 http method 수정 및 rest docs 내용을 업데이트했습니다.
-
-

fix: token reissue post mapping 및 docs 추가

---

src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostElement.java

- #299 
- 댓글 개수를 불러올 때 삭제되지 않는 댓글만 포함
<!-- 주요 변경점과 어떤 부분을 집중해서 리뷰해야 하는지 알려주세요. ->

fix: 댓글 삭제 시 댓글 수가 반영되지 않는 버그 수정

---

src/main/java/com/ssafy/ssafsound/domain/post/domain/Post.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostDetailElement.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostElement.java

- #299 
- 게시글 상세보기 댓글 수 버그 수정
- 댓글 수 세는 비즈니스 로직 Post 엔티티 내부로 분리

fix: 게시글 상세보기에도 댓글 수 버그 수정

---

src/main/java/com/ssafy/ssafsound/domain/lunch/repository/LunchPollRepository.java
src/main/java/com/ssafy/ssafsound/domain/lunch/service/LunchPollService.java
src/main/java/com/ssafy/ssafsound/domain/lunch/service/LunchService.java
src/test/java/com/ssafy/ssafsound/domain/lunch/service/LunchPollServiceTest.java
src/test/java/com/ssafy/ssafsound/domain/lunch/service/LunchServiceTest.java

- #310 
- 점심 메뉴 투표 시, 당일 투표 이력이 있다면 타 캠퍼스라도 투표가 불가능했던 버그가 있었습니다.
- 이를 해결하기 위해 투표 여부 판단에 캠퍼스 조건을 추가했습니다.
- 변경에 따라서 테스트 코드를 수정했습니다.

fix : 점심 투표 정책 변경

---

src/docs/asciidoc/notification.adoc
src/main/java/com/ssafy/ssafsound/domain/comment/service/CommentService.java
src/main/java/com/ssafy/ssafsound/domain/notification/controller/NotificationController.java
src/main/java/com/ssafy/ssafsound/domain/notification/domain/NotificationType.java
src/main/java/com/ssafy/ssafsound/domain/notification/dto/GetNotificationCursorReqDto.java
src/main/java/com/ssafy/ssafsound/domain/notification/dto/GetNotificationCursorResDto.java
src/main/java/com/ssafy/ssafsound/domain/notification/dto/GetNotificationElement.java
src/main/java/com/ssafy/ssafsound/domain/notification/dto/GetNotificationOffsetReqDto.java
src/main/java/com/ssafy/ssafsound/domain/notification/dto/GetNotificationOffsetResDto.java
src/main/java/com/ssafy/ssafsound/domain/notification/repository/NotificationCustomRepository.java
src/main/java/com/ssafy/ssafsound/domain/notification/repository/NotificationRepository.java
src/main/java/com/ssafy/ssafsound/domain/notification/repository/NotificationRepositoryImpl.java
src/main/java/com/ssafy/ssafsound/domain/notification/service/NotificationService.java
src/main/resources/static/docs/index.html
src/test/java/com/ssafy/ssafsound/domain/notification/controller/NotificationControllerTest.java
src/test/java/com/ssafy/ssafsound/global/util/fixture/NotificationFixture.java

- #320
- 일부 오타 수정
- 사용자 알림 목록 조회 오프셋 기반 페이지네이션 추가
- API 문서 최신화

feat: 사용자 알림 목록 조회 오프셋 기반 페이지네이션 추가
