SSAF-SOUND/ssaf-sound-be

src/main/java/com/ssafy/ssafsound/domain/auth/dto/AuthenticatedUser.java
src/main/java/com/ssafy/ssafsound/domain/auth/dto/LoginRequest.java
src/main/java/com/ssafy/ssafsound/domain/auth/service/token/JwtTokenProvider.java
src/main/java/com/ssafy/ssafsound/domain/auth/service/token/TokenManager.java
src/main/java/com/ssafy/ssafsound/domain/member/repository/MemberRepository.java

- #15 
- 각 도메인에서 token에 대한 인증이 이루어졌을때 인증된 유저 dto에 대한 생성
- 패키지 구조
- 토큰 생성을 위한 인터페이스 및 클래스 추가
전체적으로 dto 구조와 패키지 구조에 대해 리뷰를 해주시면 좋을 것 같습니다!
따끔한 피드백도 좋습니다 📌
예시는 다음과 같습니다.
게시판, 리크루트, 점심 투표 등등
memberId가 필요한 Domain에서는 컨트롤러 부분에서 다음과 같이 사용할 수 있습니다.
```Java
public EnvelopResponse<T> createPost(AuthenticatedUser authenticatedUser) {
...
}
```

feat: setting UserDto with authenticated

---

src/main/java/com/ssafy/ssafsound/domain/auth/controller/AuthController.java
src/main/java/com/ssafy/ssafsound/domain/auth/exception/MemberErrorInfo.java
src/main/java/com/ssafy/ssafsound/domain/auth/service/token/JwtTokenProvider.java
src/main/java/com/ssafy/ssafsound/domain/auth/validator/Authentication.java
src/main/java/com/ssafy/ssafsound/domain/auth/validator/AuthenticationArgumentResolver.java
src/main/java/com/ssafy/ssafsound/domain/auth/validator/AuthorizationExtractor.java
src/main/java/com/ssafy/ssafsound/domain/member/repository/MemberTokenRepository.java
src/main/java/com/ssafy/ssafsound/domain/member/service/MemberService.java
src/main/java/com/ssafy/ssafsound/global/config/WebMvcConfig.java
src/main/java/com/ssafy/ssafsound/global/interceptor/AuthInterceptor.java

- #49 
- Client의 요청에서 Token은 헤더에 담기지 않습니다. Http Only Secure Cookie를 통해 클라이언트에게 전달되며, 해당 쿠키를 통해 클라이언트는 서버에 전달합니다.
- 우리 API에서는  recruit, post, lunch, auth, comments, meta 와 관련된 Domain에서 GET 요청에 대해 AcccessToken이 필요하지 않다고 판단해서 인터셉터에서 통과될 수 있도록 적용했습니다.
```Java
@Component
@RequiredArgsConstructor
public class AuthInterceptor implements HandlerInterceptor {
private final JwtTokenProvider jwtTokenProvider;
@Override
public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) {
if (CorsUtils.isPreFlightRequest(request)) {
return true;
}
if (isGetMethodWithRecruitUri(request) || isGetMethodWithAuthUri(request)
|| isGetMethodWithCommentsUri(request) || isGetMethodWithLunchPollUri(request) || isGetMethodWithMetaUri(request)
|| isGetMethodWithMembersUri(request) …
```

feat: AuthenticatedMember Custom Resolver With Interceptor

---

src/main/java/com/ssafy/ssafsound/domain/auth/controller/AuthController.java
src/main/java/com/ssafy/ssafsound/domain/auth/dto/CreateAccessTokenResDto.java
src/main/java/com/ssafy/ssafsound/domain/auth/dto/CreateMemberAccessTokenResDto.java
src/main/java/com/ssafy/ssafsound/domain/auth/exception/AuthErrorInfo.java
src/main/java/com/ssafy/ssafsound/domain/auth/exception/AuthException.java
src/main/java/com/ssafy/ssafsound/domain/auth/service/AuthService.java
src/main/java/com/ssafy/ssafsound/domain/auth/service/CookieProvider.java
src/main/java/com/ssafy/ssafsound/domain/auth/service/oauth/GithubOauthProvider.java
src/main/java/com/ssafy/ssafsound/domain/auth/service/oauth/GoogleOauthProvider.java
src/main/java/com/ssafy/ssafsound/domain/auth/service/oauth/KakaoOauthProvider.java
src/main/java/com/ssafy/ssafsound/domain/auth/service/oauth/OauthProviderFactory.java
src/main/java/com/ssafy/ssafsound/domain/auth/service/token/JwtTokenProvider.java
src/main/java/com/ssafy/ssafsound/domain/auth/validator/AuthorizationExtractor.java
src/main/java/com/ssafy/ssafsound/domain/member/domain/MemberToken.java
src/main/java/com/ssafy/ssafsound/domain/member/exception/MemberErrorInfo.java
src/main/java/com/ssafy/ssafsound/domain/member/exception/MemberException.java
src/main/java/com/ssafy/ssafsound/domain/member/service/MemberService.java
src/main/java/com/ssafy/ssafsound/global/interceptor/AuthInterceptor.java

- #58 
- 로그아웃 시, 쿠키를 더이상 사용하지 못하도록 null value 설정과 함께 setMaxAge(0); 으로 로직을 제공하고 있습니다.
- 토큰이 유효한 상황에서 로그아웃을 시도한다면 데이터베이스의 존재하는 토큰도 함께 제거됩니다.
- 토큰 재발급 요청 시
1. 쿠키가 존재하지 않다면 재발급을 해줄 수 없습니다.
2. Refresh Token이 만료됐다면 재발급을 해줄 수 없습니다.
3. 만료는 되지 않았는데 해당 리프레시 토큰과 데이터베이스 존재하는 리프레시 토큰과 비교 후, 일치하지 않다면 재발급을 해줄 수 없습니다.
4. 재발급에 성공했다면, 데이터베이스에 존재하는 토큰이 갱신되고 쿠키에 담아 전송됩니다.
- 회원 가입을 했었던 유저가 로그인을 시도할 경우
1. Oauth의 고유 Identifier에 대한 검증과 OauthType에 대한 검증 로직이 추가됐습니다.
2. 기존에 가지고 있던 정보로 로그인을 다시 시도했을 경우, Member Token 조회와 함께 Access Token과 Refresh Token이 변경됩니다.
---
MemberErrorInfo와 AuthErrorInfo에 대한 분리 로직이 중간에 들어가있습니다. 커밋 기록을 보며 혼동이 올 수 있는데 양해 부탁드립니다.
다음에는 분리해서 진행하겠습니다.
회원가입을 한 유저가 로그인을 시도했을때 검증 로직을 구현하면서 의문점이 들었습니다.
기존 방식에서 Github으로 로그인 할 시, Github Name에 대한 unique Identifier가 설정되어 있었는데 유저가 github id를 바꾸면 로직에 문제가 발생한다는 …

feat: member logout with reIssue token

---

src/main/java/com/ssafy/ssafsound/domain/recruitapplication/controller/RecruitApplicationController.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/domain/RecruitApplication.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/GetRecruitApplicationsResDto.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/RecruitApplicationElement.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/repository/RecruitApplicationRepository.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/service/RecruitApplicationService.java
src/test/java/com/ssafy/ssafsound/domain/recruitapplication/service/RecruitApplicationServiceTest.java

- #38 
등록자는 자신이 작성한 리크루팅에 참여 신청한 사용자 목록을 조회할 수 있다.
등록자는 신청된 목록을 눌러 사용자의 답변을 조회할 수 있다.
조회 여부에 따라 오픈 프로필 -> 프로젝트탭 -> 등록한 프로젝트에서 표시되는 읽지않음 상태가 결정된다.
등록자는 참여 신청된 사용자 목록을 확인하고, 관심이 가는 유저의 신청에 좋아요를 눌러 다음 조회 시 상단부에 위치할 수 있도록 순서를 조절할 수 있다. (토글)
---
RecruitQuestion, RecruitQuestionReply가 차후 복수개로 늘어날 수 있음을 고려한 설계로 인해,
연관관계를 이용한 쿼리가 어렵습니다. 또한 일반적인 메서드 쿼리로는 N+1문제를 해결할 수 없기에 JPQL로 직접 쿼리를 작성했습니다.
해당 부분을 중점적으로 리뷰해주시고, 논리적 오류가 없는지 같이 봐주세요.
차후 엔티티 설계 자체를 단건으로 다시 바꾸던가, QueryDSL 등 도입을 검토해야할 것 같습니다.

feat: 등록자 리크루팅 신청 목록 조회 기능

---

src/main/java/com/ssafy/ssafsound/domain/recruit/controller/RecruitController.java
src/main/java/com/ssafy/ssafsound/domain/recruit/domain/Recruit.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/PatchRecruitReqDto.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/PostRecruitReqDto.java
src/main/java/com/ssafy/ssafsound/domain/recruit/exception/RecruitErrorInfo.java
src/main/java/com/ssafy/ssafsound/domain/recruit/service/RecruitService.java
src/test/java/com/ssafy/ssafsound/domain/recruit/dto/PostRecruitReqDtoTest.java
src/test/java/com/ssafy/ssafsound/domain/recruit/service/RecruitServiceTest.java

- #40 
- 리크루트 수정 기능 추가
- 리크루트 삭제 기능 추가
1. 리크루트 삭제의 경우 리크루트 자체는 soft delete, 연관된 데이터는 별도의 변경 없이 데이터를 유지합니다. 
2. 리크루트 수정의 경우 기존에 정한 인원 수 아래로 내릴 수 없으며, 기존에 모집했던 모집군을 삭제할 수 없습니다. 
3. 리크루트 등록 페이지에서 지원파트 선택 여부가 수정 가능해야된다면 회의 이후 코드가 일부 수정될 수 있습니다.

feat: 등록자 리크루트 수정 삭제 

---

src/main/java/com/ssafy/ssafsound/domain/recruit/controller/RecruitController.java
src/main/java/com/ssafy/ssafsound/domain/recruit/domain/Recruit.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/GetRecruitDetailResDto.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/PatchRecruitReqDto.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/RecruitLimitElement.java
src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitRepository.java
src/main/java/com/ssafy/ssafsound/domain/recruit/service/RecruitService.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/GetRecruitParticipantsResDto.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/RecruitParticipantElement.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/service/RecruitApplicationService.java
src/test/java/com/ssafy/ssafsound/domain/recruit/service/RecruitServiceTest.java
src/test/java/com/ssafy/ssafsound/domain/recruitapplication/service/RecruitApplicationServiceTest.java

- #88 
**[등록자 리크루트 참여 -> 리크루트에 등록자의 리크루트 참여 파트 column 추가]**
기존 로직  
```
리크루트 등록 
-> 리크루트 등록
-> 리크루트에서 모집하고자 하는 모집군 인원 제한 등록 (리크루트 등록자를 참여자로 포함하는 인원 수)
-> 리크루트에서 사용하는 기술 스택 등록
-> 리크루트 등록자를 참여하고자하는 모집군의 참여자로 등록 
```
변경된 로직 
```
리크루트 등록 
-> 리크루트 등록 (리크루트 등록자의 모집군은 해당 리크루트에 종속적인 값으로 변경)
-> 리크루트에서 모집하고자 하는 모집군 인원 제한 등록 (리크루트 등록자를 제외한 인원 수)
-> 리크루트에서 사용하는 기술 스택 등록
```
어제 진행된 회의에서 일부 요청 사항으로 인해 테이블에 변경 사항이 있습니다.
1. 등록, 수정하는 시점의 인원 제한은 실제로 등록자가 모집 하고자 하는 인원만 포함시키고, 자기 자신을 포함시키지 않는다.
2. 리크루트를 조회하는 경우, 등록자를 포함한 참여자 명단과, 등록자를 포함한 인원 제한 수를 보여줘야한다.
3. 등록자가 참여하는 모집 타입은 수정이 가능해야한다.

refactor: 리크루트 데이터 베이스 컬럼 추가 사항 반영

---

src/main/java/com/ssafy/ssafsound/domain/auth/validator/AuthenticationArgumentResolver.java
src/main/java/com/ssafy/ssafsound/domain/auth/validator/AuthorizationExtractor.java
src/main/java/com/ssafy/ssafsound/domain/lunch/controller/LunchController.java
src/main/java/com/ssafy/ssafsound/domain/lunch/dto/GetLunchListReqDto.java
src/main/java/com/ssafy/ssafsound/domain/lunch/dto/GetLunchListResDto.java
src/main/java/com/ssafy/ssafsound/domain/lunch/exception/LunchErrorInfo.java
src/main/java/com/ssafy/ssafsound/domain/lunch/repository/LunchPollRepository.java
src/main/java/com/ssafy/ssafsound/domain/lunch/service/LunchService.java
src/main/resources/application-local.yml

- #66
- @Authenicate 어노테이션의 extractor 로직이 변경되었습니다. 다음은 변경된 AuthorizationExtractor 클래스의 extractToken 메소드입니다.
```java
public static String extractToken(String tokeType, HttpServletRequest request) {
Cookie[] cookies = request.getCookies();
// cookie 없는 경우(미인증)
if (cookies == null) return null;
for (Cookie cookie : cookies) {
if (cookie.getName().equals(tokeType)) {
return cookie.getValue();
}
}
return null;
}
```
위 코드는 기존에는 cookies가 아예 없는 경우는 NullPointerException이 발생하며, 토큰을 getName으로 뽑을 수 없는 경우에는AuthException을 던지고 있었습니다.
그러나 그냥 null 값을 AuthenicationArgumentResolver에 반환해주도록 변경했습니다.
다음은 AuthenicationArgumentResolver에서 extractToken 호출하던 메소드입니다.
기존에는 if 문이 없었지만 If문을 추가하여 미인증 GET 요청의 경우 컨트롤러에 초기화되지 않은 AuthenticatedMember를 넣어줄 수 있도록 합니다.
```java
public Object resolveArgument(MethodParameter …
```

fix: 점심 메뉴 api 업데이트

---

src/main/java/com/ssafy/ssafsound/domain/post/controller/PostController.java
src/main/java/com/ssafy/ssafsound/domain/post/domain/Post.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/PostPutUpdateReqDto.java
src/main/java/com/ssafy/ssafsound/domain/post/exception/PostErrorInfo.java
src/main/java/com/ssafy/ssafsound/domain/post/repository/PostRepository.java
src/main/java/com/ssafy/ssafsound/domain/post/service/PostService.java

- #77 
- 게시글 수정 기능 구현
- 게시글 삭제 쿼리 복구
- 예외 처리
게시글 수정과 게시글 삭제에서 게시글 정보를 가져오는 쿼리에 Fetch join을 적용하고
이후에 memberId와 비교한 이유는 사용자 권한 예외를 발생하기 위함입니다.
memberId와 함께 post정보를 불러오면 작성자가 아닌 사용자는 게시글 정보가 나오지 않기 때문에
권한이 없는 사용자가 접근했을때 예외를 처리할 방법이 없어지게 됩니다.
예시로) 기존 방법은 게시글이 있는 번호를 넘겨줬을 때 "게시글이 존재하지 않습니다" 라는 에러를 보게 됩니다.
JPA 쿼리와 게시글 수정 흐름을 위주로 리뷰해주시면 감사하겠습니다.

feat: 게시글 수정 기능 구현

---

src/main/java/com/ssafy/ssafsound/domain/comment/controller/CommentController.java
src/main/java/com/ssafy/ssafsound/domain/comment/domain/Comment.java
src/main/java/com/ssafy/ssafsound/domain/comment/domain/CommentNumber.java
src/main/java/com/ssafy/ssafsound/domain/comment/dto/PostCommentWriteReqDto.java
src/main/java/com/ssafy/ssafsound/domain/comment/exception/CommentErrorInfo.java
src/main/java/com/ssafy/ssafsound/domain/comment/exception/CommentException.java
src/main/java/com/ssafy/ssafsound/domain/comment/repository/CommentNumberRepository.java
src/main/java/com/ssafy/ssafsound/domain/comment/repository/CommentRepository.java
src/main/java/com/ssafy/ssafsound/domain/comment/service/CommentService.java
src/main/java/com/ssafy/ssafsound/global/advice/ExceptionControllerAdvice.java

- #92 
- 댓글 작성 기능 구현
- 익명 번호를 부여하기 위한 comment_number 테이블 생성
- comment 익명여부, 댓글 번호 fk 추가
익명1, 익명2, 익명3을 위해서 댓글 번호 테이블 및 엔티티를 추가하였고, 이를 댓글마다 join하기 위해 ManyToOne관계를 댓글 엔티티에 추가했습니다.
댓글 기능의 전체적인 구현 시나리오는 다음과 같습니다.
- 댓글 작성
1. 댓글 번호 테이블에 (postid, memberid)에 해당하는 데이터가 없으면, comment_number에 데이터개수 + 1로 추가(익명번호)
2. commentGroup은 자기자신
- 대댓글 작성
1. 댓글 작성과 동일
2. commentGroup은 쿼리스트링으로 들어온 getReferenceById(commentId)로 채움
- 댓글 목록 조회
1. 댓글, 대댓글 관계없이 댓글 전체를 (id, Group_id)로 정렬해서 조회(replies 리스트 사용x)
2. Pageable을 활용한 페이지네이션
3. 댓글, 대댓글 구분은 id와 commentGroupId가 같으면 부모, 다르면 대댓글
커밋이 꼬여버려서 다시 pr 올립니다. 코드는 동일하지만, 이전 피드백은 수정된 상태입니다.

feat: 댓글 작성 기능 구현

---

src/main/java/com/ssafy/ssafsound/domain/post/controller/PostController.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostSearchElement.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostSearchReqDto.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostSearchResDto.java
src/main/java/com/ssafy/ssafsound/domain/post/exception/PostErrorInfo.java
src/main/java/com/ssafy/ssafsound/domain/post/repository/PostRepository.java
src/main/java/com/ssafy/ssafsound/domain/post/service/PostService.java

- #123 
- 게시글 검색 기능 구현
- 게시글 keyword 검증(한글자 or 공백만 있으면 검색 안됨)
게시글 검색은 현재 와일드 카드기반 like 검색을 수행합니다.
공백 포함없이 키워드가 들어가는 게시글을 다 검색합니다!
```
@Query("SELECT p FROM post p " +
"JOIN FETCH p.board b " +
"JOIN FETCH p.member " +
"WHERE (REPLACE(p.title, ' ', '') LIKE CONCAT('%', :keyword, '%') " +
"OR REPLACE(p.content, ' ', '') LIKE CONCAT('%', :keyword, '%')) " +
"AND b.id = :boardId ")
List<Post> findWithDetailsFetchByBoardIdAndKeyword(@Param("boardId") Long boardId, @Param("keyword") String keyword, Pageable pageable);
```
게시글 검색 관련 쿼리문입니다. 피드백 적극 환경합니다.
차후 성능 최적화가 필요하다면, Elasticsearch를 고려해볼 수 있을거 같습니다!

feat: 게시글 검색 기능 구현

---

src/main/java/com/ssafy/ssafsound/domain/lunch/controller/LunchController.java
src/main/java/com/ssafy/ssafsound/domain/lunch/domain/LunchPoll.java
src/main/java/com/ssafy/ssafsound/domain/lunch/dto/GetLunchListReqDto.java
src/main/java/com/ssafy/ssafsound/domain/lunch/repository/LunchPollRepository.java
src/main/java/com/ssafy/ssafsound/domain/lunch/service/LunchPollService.java
src/main/java/com/ssafy/ssafsound/domain/lunch/service/LunchService.java
src/main/java/com/ssafy/ssafsound/global/config/TimeConfig.java
src/main/resources/application.yml
src/test/java/com/ssafy/ssafsound/domain/lunch/service/LunchPollServiceTest.java
src/test/java/com/ssafy/ssafsound/domain/lunch/service/LunchServiceTest.java
src/test/java/com/ssafy/ssafsound/global/util/NullableConverter.java

- #
- 테스트 코드가 너무 길어져서 기존에 LunchService에 몰려있던 Lunch와 LunchPoll 로직을 LunchService와 LunchPollService로 분리했습니다.
- assertThrows로 예외 테스트 시에 예외 종류가 도메인마다 똑같기 때문에, 구분을 위해서 Exception의 enum 필드인 ErrorInfo 까지 검증했습니다.
- 기존에 memberId를 이용해 직접 쿼리를 보내던 방식에서, MemberRepository에서 Member 엔티티를 조회해서 사용하는 방식으로 변경했습니다.
- @CsvSource를 이용하여 테스트 시에 디폴트 컨버터로는 인풋 파라미터 객체 값으로 null을 할당할 수 없습니다. 따라서 NullableConverter를 구현했고, test.java.com.ssafy.ssafsound.global.util에 위치시켰습니다. 사용 방법은 다음과 같습니다.
```java
void SampleTest (@ConvertWith(NullableConverter.class) Long memberId, String inputCampus, LocalDate inputDate, Long outputPolledAt) { ....
``` 
- 타임머신 테스트를 위해서 TimeConfig를 추가했습니다. 기존에는 현재 시간이라는 값을 로직에서 사용할 때는 LocalDateTime.now() 라는 static 메소드를 사용했습니다. 하지만 static 메소드는 테스트 시에 모킹이 어렵기 때문에, Clock이라는 객체를 주입받아서 Clock을 이용해서 현재시간을 받는 …

test : 점심 메뉴 테스트 및 리팩토링

---

src/main/java/com/ssafy/ssafsound/domain/member/controller/MemberController.java
src/main/java/com/ssafy/ssafsound/domain/member/domain/Member.java
src/main/java/com/ssafy/ssafsound/domain/member/domain/MemberLink.java
src/main/java/com/ssafy/ssafsound/domain/member/domain/MemberProfile.java
src/main/java/com/ssafy/ssafsound/domain/member/dto/PostMemberLink.java
src/main/java/com/ssafy/ssafsound/domain/member/dto/PutMemberLink.java
src/main/java/com/ssafy/ssafsound/domain/member/dto/PutMemberProfileReqDto.java
src/main/java/com/ssafy/ssafsound/domain/member/repository/MemberLinkRepository.java
src/main/java/com/ssafy/ssafsound/domain/member/repository/MemberProfileRepository.java
src/main/java/com/ssafy/ssafsound/domain/member/repository/MemberSkillRepository.java
src/main/java/com/ssafy/ssafsound/domain/member/service/MemberService.java

- #133 
- 멤버는 자신의 프로필에 대한 자기소개서를 작성할 수 있습니다.
- 멤버는 자신의 기술 스택에 대해 작성할 수 있습니다.
- 멤버는 자신의 소개 링크에 대해 작성할 수 있습니다.
MemberSkill과 MemberLink는 양방향 Mapping을 가지고 있습니다.
만약, Member가 삭제된다면 MemberSkill과 MemberLink도 함께 삭제될 수 있도록
```Java
orphanRemoval = true
```
를 지정했습니다.
***헷갈릴 수 있는 비즈니스 로직***
Http Method Put을 통해 해당 API를 호출합니다.
따라서, 변경 사항이 있을 경우 때문에 MemberProfile 같은 경우는 1:1 Mapping이기 때문에 이미 존재한다면 수정
MemberSkills과 MemberLink의 경우는 이미 존재한다면, 모두 삭제하고 새롭게 데이터베이스에 저장합니다.
* CGLIB PROXY 객체를 생성하는 부분에 있어서 오해
이미 알고 있던 내용이라면 넘어가셔도 되지만 제가 잘못 이해하고 있던 부분을 공유 해드리고, 도움이 된다면 좋을 것 같아요!
@Transactional 애노테이션이 하나라도 붙어있는 클래스가 존재한다면 Spring에서 Application을 실행할때, 해당 클래스를 Proxy 객체로 생성하여 빈으로 등록합니다.
만약 @Transactional 애노테이션이 하나라도 붙어있지 않다면 실제 객체를 생성하여 빈으로 등록합니다.
---
마주쳤던 이슈 상황 
```Java
package …
```

feat: member input portfolio

---

src/main/java/com/ssafy/ssafsound/domain/recruit/domain/GetRecruitLimitDetail.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/GetRecruitDetailResDto.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/PostRecruitReqDto.java
src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitLimitationRepository.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/GetRecruitParticipantsResDto.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/ParticipantElement.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/RecruitParticipantElement.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/service/RecruitApplicationService.java
src/test/java/com/ssafy/ssafsound/domain/recruitapplication/service/RecruitApplicationServiceTest.java

- #129 
1. 리크루트 단건 조회
현재 참여중인 인원의 숫자 추가 (currentNumber 추가)
2. 리크루트 참여자 목록 조회
→ 모집 파트별 인원 제한 추가 및 데이터 구조 변경 
기존 -> 모든 참여자에 RecruitType를 가지는 형태 
```javascript
"recruitType":  "기획/디자인",
"memberId": 2,
"nickName": "kds",
"isMajor": true,
"ssafyInfo": {
"semester": 9,
"campus": "서울",
"certificationState": "CERTIFIED",
"majorTrack": "Java"
}
```
변경 
```jacascript
{
"code": "200",
"message": "success",
"data": {
"recruitTypes": {
"기획/디자인": {
"limit": 3,
"members": [
{
"memberId": 2,
"nickName": "kds",
"isMajor": true,
"ssafyInfo": {
"semester": 9,
"campus": "서울",
"certificationState": "CERTIFIED",
"majorTrack": "Java"
}
},
{
"memberId": 1,
"nickName": "khs",
"isMajor": true,
"ssafyInfo": {
"semester": 9,
"campus": "서울",
"certificationState": "CERTIFIED",
"majorTrack": "Java"
}
}
]
}
}
}
}
``` …

refactor: 리크루트 참여자 조회 수정

---

src/main/java/com/ssafy/ssafsound/domain/recruit/domain/RecruitLimitation.java
src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitLimitationRepository.java
src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitSkillRepository.java
src/main/java/com/ssafy/ssafsound/domain/recruit/service/RecruitService.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/repository/RecruitApplicationRepository.java
src/test/java/com/ssafy/ssafsound/domain/recruit/service/RecruitServiceTest.java

- #136
리크루트 모집 인원 수정 기능 변경
- 기존
리크루트 모집 인원제한은 수정 시, 증가만 가능하며, 모집파트 또한 추가만 가능하다.
변경
```
리크루트 모집 인원은 제한은, 해당 파트에 모집 완료된 인원 아래로는 수정할 수 없지만, 그 외의 감소와 증가는 모두 가능하다.
리크루트 모집파트는 삭제 또는 추가가 가능하다. 단 해당 파트에 모집완료 인원이 존재하는 경우 삭제할 수 없다.
리크루트 모집파트를 삭제하는 경우, 연관된 리크루트 모집신청은 모두 삭제되어야한다.
```

refactor: 리크루트 수정 

---

src/main/java/com/ssafy/ssafsound/domain/member/controller/MemberController.java
src/main/java/com/ssafy/ssafsound/domain/member/domain/Member.java
src/main/java/com/ssafy/ssafsound/domain/member/dto/GetMemberResDto.java
src/main/java/com/ssafy/ssafsound/domain/member/dto/PatchMemberDefaultInfoReqDto.java
src/main/java/com/ssafy/ssafsound/domain/member/dto/PostMemberInfoReqDto.java
src/main/java/com/ssafy/ssafsound/domain/member/exception/MemberErrorInfo.java
src/main/java/com/ssafy/ssafsound/domain/member/service/MemberConstantProvider.java
src/main/java/com/ssafy/ssafsound/domain/member/service/MemberService.java
src/main/java/com/ssafy/ssafsound/global/config/MagicNumberConfig.java
src/test/java/com/ssafy/ssafsound/domain/member/service/MemberServiceTest.java

- #156 
- 이 비즈니스 로직의 핵심은 member의 기본 정보인 ssafyMember (true or false): 싸피멤버인지 아닌지 , semester (1,2, 3 .... 9) : 기수 정보, majorTrack(Embedded, Java, Python ... ) 등 전공 정보를 변경하는 일을 합니다.
따라서, member라는 entity가 할 수 있는 책임이라고 생각해서
```Java
@Transactional
public void patchMemberDefaultInfo(
AuthenticatedMember authenticatedMember,
PatchMemberDefaultInfoReqDto patchMemberDefaultInfoReqDto) {
Member member = memberRepository.findById(authenticatedMember.getMemberId())
.orElseThrow(() -> new MemberException(MemberErrorInfo.MEMBER_NOT_FOUND_BY_ID));
member.exchangeDefaultInformation(patchMemberDefaultInfoReqDto, metaDataConsumer);
}
```
exchangeDefaultInformation 메서드를 통해 일을 수행하고 있습니다.
exchangeDefaultInformation의 내부 로직이 서비스 메서드 내에 노출되는 것이 좋은지 함께 의견을 내주시면 감사할 것 같습니다.
---
ssafyMember: true 일 경우, 기수정보가 null로 …

feat: member 기본정보 수정 API

---

src/main/java/com/ssafy/ssafsound/domain/chat/controller/ChatController.java
src/main/java/com/ssafy/ssafsound/domain/chat/domain/Talker.java
src/main/java/com/ssafy/ssafsound/domain/chat/dto/DeleteChatResDto.java
src/main/java/com/ssafy/ssafsound/domain/chat/exception/ChatErrorInfo.java
src/main/java/com/ssafy/ssafsound/domain/chat/exception/ChatException.java
src/main/java/com/ssafy/ssafsound/domain/chat/repository/TalkerRepository.java
src/main/java/com/ssafy/ssafsound/domain/chat/service/ChatRoomService.java

- 채팅 삭제 api 및 에러코드 추가
- #103 
- 채팅방 삭제는 ChatRoom을 삭제하는 것이 아닌 Talker의 startedAt 필드를 최신화 하는 형태로 soft delete 됩니다. 삭제를 하지 않는 채팅상대의 경우 영향이 없어야하기 때문입니다. 따라서 유저는 채팅방 내부 메세지를 조회할 때 자신의 startedAt의 시간 이후의 메시지만 조회가 가능합니다.

feat : 채팅방 삭제 api 추가

---

build.gradle
src/main/java/com/ssafy/ssafsound/domain/post/controller/PostController.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostElement.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostHotElement.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostHotReqDto.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostHotResDto.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostHotSearchReqDto.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostMyElement.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostMyReqDto.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostMyResDto.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostReqDto.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostResDto.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostSearchReqDto.java
src/main/java/com/ssafy/ssafsound/domain/post/repository/HotPostCustomRepository.java
src/main/java/com/ssafy/ssafsound/domain/post/repository/HotPostCustomRepositoryImpl.java
src/main/java/com/ssafy/ssafsound/domain/post/repository/HotPostRepository.java
src/main/java/com/ssafy/ssafsound/domain/post/repository/PostCustomRepository.java
src/main/java/com/ssafy/ssafsound/domain/post/repository/PostCustomRepositoryImpl.java
src/main/java/com/ssafy/ssafsound/domain/post/repository/PostRepository.java
src/main/java/com/ssafy/ssafsound/domain/post/service/PostService.java
src/main/java/com/ssafy/ssafsound/global/config/QueryDslConfig.java

- #149 
- 커서 기반의 페이지 네이션 방식으로 수정
- Hot 게시글 목록 조회
- Hot 게시글 검색
- 게시글 목록 조회
- 게시글 검색
- 나의 게시글 목록 조회
- QueryDsl 설정 추가
목록 조회 관련 모든 기능을 커서 기반의 페이지네이션으로 수정했습니다. 이를 위해서는 QueryDsl로 쿼리문을 작성할 필요성이 있었습니다. 
요청데이터에 쿼리스트링의 page -> cursor필드로 수정하였습니다. 단, cursor 필드는 -1이 처음 페이지를 의미합니다.
- 요청 데이터의 cursor
@khs960616 한성님은 null을 처음 페이지를 의미하도록 하였지만, 저는 -1로 두었는데 그 이유는 null값을 쿼리스트링으로 넣기 위해서는 null임을 체크한 후 Long타입의 cursor에 null을 할당하는 분기문 처리를 수행해야 하기 때문입니다.
이 부분은 통일하면 좋을거 같습니다.
- 응답 데이터의 cursor
현재 size만큼의 목록이 조회되고, 다음 페이지에 해당하는 데이터가 존재하면 마지막의 cursor 값이 응답으로 전달됩니다.
예를들어 cursor=-1 size=3 을 두었을때 id가 9, 8, 7로 데이터가 출력된다면 응답 데이터의 cursor값은 7이 됩니다.
만약 다음 페이지에 해당하는 데이터가 없다면 null이 응답됩니다.
- build.gradle에 Querydsl 설정 추가
```
plugins {
// querydsl 플러그인 추가
id "com.ewerk.gradle.plugins.querydsl" version "1.0.10"
}
```
플러그인에 querydsl을 …

feat: 목록 조회 관련 기능 커서 기반으로 페이징 변경

---

src/main/java/com/ssafy/ssafsound/domain/member/controller/MemberController.java
src/main/java/com/ssafy/ssafsound/domain/member/domain/Member.java
src/main/java/com/ssafy/ssafsound/domain/member/dto/GetMemberDefaultInfoResDto.java
src/main/java/com/ssafy/ssafsound/domain/member/dto/GetMemberPortfolioResDto.java
src/main/java/com/ssafy/ssafsound/domain/member/dto/GetMemberPublicProfileResDto.java
src/main/java/com/ssafy/ssafsound/domain/member/dto/PatchMemberNicknameReqDto.java
src/main/java/com/ssafy/ssafsound/domain/member/dto/PatchMemberProfilePublicReqDto.java
src/main/java/com/ssafy/ssafsound/domain/member/dto/PatchMemberPublicProfileReqDto.java
src/main/java/com/ssafy/ssafsound/domain/member/dto/PutMemberPortfolioReqDto.java
src/main/java/com/ssafy/ssafsound/domain/member/service/MemberService.java
src/test/java/com/ssafy/ssafsound/domain/member/service/MemberServiceTest.java

- #166 
-  멤버의 공개 여부를 따로 조회할 수 있는 api GET /members/public-profile 로 추가했습니다.
마이페이지에서 조회할 수 있는 데이터는
사용자의 기본 정보, 사용자 포트폴리오, 나의 프로젝트/스터디 이기 때문에
Front입장에서는 먼저 공개 여부를 조회하고 데이터를 가져올 수 있도록 합의했습니다.
- 공개여부 필드에 대해 publicPortfolio -> publicProfile로 변경했습니다.
- PutMemberProfileDto라는 네이밍에서 -> 포트폴리오 입력이기 때문에 PutMemberPortfolioDto 로 변경했습니다.
- memberId에 대해 조회하는 로직이 공통적이라 생각해서 따로 메서드로 분리했습니다.
- 메서드 줄바꿈에 대해 수정된 부분이 몇몇 존재합니다. -> 따로 작업했어야 했는데 작업하면서 너무 보기 불편해서 같이 했네요 주의하겠습니다.

refactor: member의 프로필 공개 여부에 따른 로직 리팩토링

---

src/docs/asciidoc/metadata.adoc
src/test/java/com/ssafy/ssafsound/domain/meta/controller/MetaControllerTest.java
src/test/java/com/ssafy/ssafsound/domain/meta/fixture/ProductionMetaDataFixture.java

- #197 
- Rest Docs(문서화)을 위한 메타데이터 컨트롤러 테스트 추가
- 실제 운영 기반 데이터 반영을 위한 픽스쳐 추가
1. 해당 테스트의 경우 실제 운영 환경에서 활용되는 데이터가 명시적으로 제공되어야하므로, 임의의 MetaData 객체를 생성하기보다, 
기존 enum클래스를 기반으로 fixture을 만들도록 구성했습니다. 해당 부분에 문제가 없을지 같이 고민해주세요.
2. MetaControllerTest.java에서, enumMetaDataConsumer에 parameter로 any()를 넣은 경우, 문서화를 위한 코드이긴 하지만
메타데이터의 특성상 테스트코드의 의미가 이상하다고 느꼈습니다.  따라서 이 경우에는 실제로 들어가야될 parameter를 넣었습니다. (차후 Request Body, Query String으로 부터 받는 DTO를 넣는 경우에는 any로 mocking 해서 넣으려고 해요.)  이 부분 문제 없을지 확인 부탁드립니다.

[TEST] MetaDataController Rest Docs With Rest Assured 

---

src/docs/asciidoc/member.adoc
src/main/java/com/ssafy/ssafsound/domain/auth/controller/AuthController.java
src/main/java/com/ssafy/ssafsound/domain/member/controller/MemberController.java
src/main/java/com/ssafy/ssafsound/domain/member/domain/Member.java
src/main/java/com/ssafy/ssafsound/domain/member/dto/PatchMemberMajorReqDto.java
src/main/java/com/ssafy/ssafsound/domain/member/dto/PatchMemberMajorTrackReqDto.java
src/main/java/com/ssafy/ssafsound/domain/member/exception/MemberErrorInfo.java
src/main/java/com/ssafy/ssafsound/domain/member/service/MemberService.java
src/main/resources/static/docs/index.html
src/test/java/com/ssafy/ssafsound/domain/member/controller/MemberControllerTest.java
src/test/java/com/ssafy/ssafsound/domain/member/service/MemberServiceTest.java
src/test/java/com/ssafy/ssafsound/global/util/fixture/MemberFixture.java

- #157 
- 큰 구현 사항은 없습니다. 전공자 유무에 대해서는 싸피생과 상관없이 변경할 수 있어야 하기 때문에 멤버 정보 인증 및 Client의 전공자 유무 Boolean값을 받고 있습니다.
- 전공자 트랙에 대해서 변경할 수 있으나 싸피생만 변경할 수 있습니다. 따라서 싸피생 유무 검증, 전공트랙에 대한 Validation은 MetaDataConsumer가 처리합니다.
- 서비스 및 컨트롤러 테스트를 추가했습니다.

feat: 멤버의 전공자 유무 및 전공트랙 수정 API 추가

---

src/main/java/com/ssafy/ssafsound/SsafsoundApplication.java
src/main/java/com/ssafy/ssafsound/domain/recruit/exception/RecruitErrorInfo.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/controller/RecruitApplicationController.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/domain/MatchStatus.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/repository/RecruitApplicationRepository.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/service/RecruitApplicationService.java
src/main/resources/static/docs/index.html
src/test/java/com/ssafy/ssafsound/domain/recruitapplication/controller/RecruitApplicationControllerTest.java
src/test/java/com/ssafy/ssafsound/domain/recruitapplication/service/RecruitApplicationServiceTest.java
src/test/java/com/ssafy/ssafsound/global/util/fixture/RecruitApplicationFixture.java

- #238
```
기존
WAITING_REGISTER_APPROVE, WAITING_APPLICANT, DONE, REJECT, CANCEL
```
```
변경 후
WAITING_REGISTER_APPROVE, DONE, REJECT, CANCEL
```
**목적**
컴포넌트 재사용성 및 로직 단순화를 위한 기획 변경
```
기존
리크루트 참여자는 등록자의 수락을 받고, 이후 최종적으로 자신이 참여 확정을 누름으로써 리쿠르트 모집글에 참여한다.
```
```
변경
리크루트 참여자는 등록자가 수락하는 경우, 리쿠르트 모집글에 참여한다.
리크루트 등록자는 참여 확정이 된 리크루트 참여자를 참여자 명단에서 수정할 수 있다.(추방할 수 있어야한다.)
참여 대기중이거나, 확정이 되지 않은 리크루트글에 대해 사용자는 거절당한 이후에 다시 리크루트 참여를 신청할 수 있다.
```

refactor: recruit application matchstatus

---

src/main/java/com/ssafy/ssafsound/domain/recruit/controller/RecruitController.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/GetRecruitDetailResDto.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/GetRecruitsReqDto.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/GetRecruitsResDto.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/PostRecruitReqDto.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/RecruitElement.java
src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitDynamicQueryRepository.java
src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitDynamicQueryRepositoryImpl.java
src/main/java/com/ssafy/ssafsound/domain/recruit/service/RecruitService.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/domain/MatchStatus.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/domain/RecruitApplication.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/GetRecruitParticipantsResDto.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/ParticipantElement.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/PostRecruitApplicationReqDto.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/RecruitApplicationElement.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/RecruitParticipantElement.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/repository/RecruitApplicationRepository.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/service/RecruitApplicationService.java
src/main/resources/static/docs/index.html
src/test/java/com/ssafy/ssafsound/domain/recruit/controller/RecruitControllerTest.java
src/test/java/com/ssafy/ssafsound/domain/recruit/service/RecruitServiceTest.java
src/test/java/com/ssafy/ssafsound/domain/recruitapplication/controller/RecruitApplicationControllerTest.java
src/test/java/com/ssafy/ssafsound/domain/recruitapplication/service/RecruitApplicationServiceTest.java
src/test/java/com/ssafy/ssafsound/global/util/fixture/RecruitApplicationFixture.java
src/test/java/com/ssafy/ssafsound/global/util/fixture/RecruitFixture.java

- #178
- 세부 구현 사항 1
- 마이프로필 리크루트 조회 쿼리 추가 
- 프론트 요청사항 반영으로 인한 데이터 필드 수정

feat: 마이프로필 및 리크루트 데이터포맷 수정 

---

src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/GetRecruitApplicationDetailResDto.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/GetRecruitApplicationsResDto.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/ParticipantElement.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/PendingRecruitApplicationElement.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/dto/RecruitParticipantElement.java
src/main/resources/static/docs/index.html
src/test/java/com/ssafy/ssafsound/domain/recruitapplication/controller/RecruitApplicationControllerTest.java

- #249 
- 세부 구현 사항 1
- 프론트 작업시 날짜의 의미를 좀 더 명확히 표기 요청으로 인한 필드명 수정 
-

refactor: 리크루트 신청 신청시간, 확정시간 필드명 수정

---

src/main/java/com/ssafy/ssafsound/batch/config/PostBatchConfig.java
src/main/java/com/ssafy/ssafsound/batch/tasklet/PostTasklet.java
src/main/java/com/ssafy/ssafsound/domain/comment/domain/Comment.java
src/main/java/com/ssafy/ssafsound/domain/comment/repository/CommentRepository.java
src/main/java/com/ssafy/ssafsound/domain/comment/service/CommentService.java
src/main/java/com/ssafy/ssafsound/domain/member/dto/AuthorElement.java
src/main/java/com/ssafy/ssafsound/domain/post/domain/HotPost.java
src/main/java/com/ssafy/ssafsound/domain/post/domain/PostLike.java
src/main/java/com/ssafy/ssafsound/domain/post/domain/PostScrap.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostReqDto.java
src/main/java/com/ssafy/ssafsound/domain/post/repository/HotPostRepository.java
src/main/java/com/ssafy/ssafsound/domain/post/service/PostConstantProvider.java
src/main/java/com/ssafy/ssafsound/domain/post/service/PostService.java
src/main/java/com/ssafy/ssafsound/global/config/MagicNumberConfig.java
src/test/java/com/ssafy/ssafsound/domain/post/service/PostServiceTest.java

- #169 
- 게시글 목록 조회 서비스 테스트
- 게시글 상세 보기 서비스 테스트
- 게시글 좋아요 서비스 테스트
- 게시글 스크랩 서비스 테스트
- 항상 댓글이 수정됨으로 나오는 버그 수정
- 핫게시글이 중복으로 등록되는 버그 수정

feat: Post 도메인 Service 단위 테스트

---

src/main/java/com/ssafy/ssafsound/domain/recruit/controller/RecruitController.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/AddParticipantDto.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/AppliedRecruit.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/AppliedRecruitElement.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/GetMemberAppliedRecruitsReqDto.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/GetMemberAppliedRecruitsResDto.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/GetMemberJoinRecruitsReqDto.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/GetRecruitsReqDto.java
src/main/java/com/ssafy/ssafsound/domain/recruit/exception/RecruitErrorInfo.java
src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitDynamicQueryRepository.java
src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitDynamicQueryRepositoryImpl.java
src/main/java/com/ssafy/ssafsound/domain/recruit/service/RecruitService.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/controller/RecruitApplicationController.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/repository/RecruitApplicationComplexQueryRepository.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/repository/RecruitApplicationComplexQueryRepositoryImpl.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/repository/RecruitApplicationRepository.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/service/RecruitApplicationService.java
src/test/java/com/ssafy/ssafsound/domain/recruit/controller/RecruitControllerTest.java
src/test/java/com/ssafy/ssafsound/domain/recruit/service/RecruitServiceTest.java
src/test/java/com/ssafy/ssafsound/domain/recruitapplication/controller/RecruitApplicationControllerTest.java
src/test/java/com/ssafy/ssafsound/domain/recruitapplication/service/RecruitApplicationServiceTest.java
src/test/java/com/ssafy/ssafsound/global/util/fixture/RecruitApplicationFixture.java
src/test/java/com/ssafy/ssafsound/global/util/fixture/RecruitFixture.java

- #251
- 세부 구현 사항 1
1. 사용자 지원한 리크루트 목록 조회 (-> 리크루팅 목록 조회와 동일, appiedAt, matchStatus 추가) (전체/ 대기중/ 수락됨/ 거절됨)
2. 사용자 참여중인 리쿠르팅 목록 조회 (-> 리크루팅 목록 조회와 동일한 응답 데이터)
3. 사용자 리크루팅 신청서 조회 (리크루팅 디테일에서 application 상세조회)
4. 사용자 스크랩 리크루팅 목록 조회 (-> 리크루팅 목록 조회와 동일한 응답 데이터)
5. 등록자 거절한 리크루팅 신청 목록 조회 (-> 리크루트 참여 신청 목록 조회와 동일한 응답 데이터)
주말 간 배포를 위해 서비스 테스트 코드는 리팩토링과 함께 진행하겠습니다.

feat: 리크루트 조회 api 일괄 추가 작업

---

src/main/java/com/ssafy/ssafsound/domain/auth/controller/AuthController.java
src/main/java/com/ssafy/ssafsound/domain/member/dto/SSAFYInfo.java
src/main/java/com/ssafy/ssafsound/domain/member/service/MemberService.java
src/test/java/com/ssafy/ssafsound/domain/auth/controller/AuthControllerTest.java
src/test/java/com/ssafy/ssafsound/domain/member/controller/MemberControllerTest.java
src/test/java/com/ssafy/ssafsound/domain/member/service/MemberServiceTest.java
src/test/java/com/ssafy/ssafsound/global/util/fixture/AuthFixture.java
src/test/java/com/ssafy/ssafsound/global/util/fixture/CommentFixture.java
src/test/java/com/ssafy/ssafsound/global/util/fixture/MemberFixture.java
src/test/java/com/ssafy/ssafsound/global/util/fixture/PostFixture.java
src/test/java/com/ssafy/ssafsound/global/util/fixture/RecruitApplicationFixture.java
src/test/java/com/ssafy/ssafsound/global/util/fixture/RecruitCommentFixture.java
src/test/java/com/ssafy/ssafsound/global/util/fixture/RecruitFixture.java

- #245 
- isSSAFYMemberInformation 에서의 ssafyInfo를 제공하기 위한 null 검증을 추가했습니다.
- memberFixture를 통한 리팩토링을 진행했습니다.
-

test: memberService 테스트 코드 리팩토링 및 ssafyInfo null 처리 추가

---

src/main/java/com/ssafy/ssafsound/domain/recruit/dto/GetRecruitDetailResDto.java
src/main/java/com/ssafy/ssafsound/domain/recruit/dto/Participant.java
src/main/java/com/ssafy/ssafsound/domain/recruit/service/RecruitService.java
src/main/resources/static/docs/index.html
src/test/java/com/ssafy/ssafsound/domain/recruit/controller/RecruitControllerTest.java
src/test/java/com/ssafy/ssafsound/global/util/fixture/RecruitFixture.java

- 리크루트 상세 조회 시 내가 쓴 글인지 여부 추가 
- 리크루트 참여자 목록 조회시 전공자여부 필드 major -> isMajor로 일괄되게 네이밍 수정 (프론트 요청사항)

fix: 리크루트 디테일 조회 시 내가 쓴 글 여부 추가 및 목록 조회 전공자 여부 필드명 일괄 수정 

---

src/main/java/com/ssafy/ssafsound/domain/auth/controller/AuthController.java
src/main/java/com/ssafy/ssafsound/domain/auth/service/AuthService.java
src/main/java/com/ssafy/ssafsound/domain/auth/service/token/JwtTokenProvider.java
src/main/java/com/ssafy/ssafsound/domain/auth/validator/AuthenticationArgumentResolver.java

- #258 
- accessToken parseClaims 과정에서 발생할 수 있는 예외 케이스를 try - catch를 통해 잡았습니다.
- 어떠한 케이스에도 로그아웃 요청 시, Cookie Setting을 비울 수 있도록 코드를 리팩토링 했습니다.
try - catch 리팩토링 코드 보시면서 의견 주신다면 감사합니다.

hotfix: logout 요청 시 토큰 만료로 인한 비즈니스 로직 실패 케이스 수정

---

src/main/java/com/ssafy/ssafsound/domain/board/dto/GetBoardElement.java
src/main/java/com/ssafy/ssafsound/domain/board/repository/BoardRepository.java
src/main/java/com/ssafy/ssafsound/domain/board/service/BoardService.java
src/main/java/com/ssafy/ssafsound/domain/post/domain/Post.java
src/main/java/com/ssafy/ssafsound/domain/post/domain/PostImage.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/ImageInfo.java
src/main/java/com/ssafy/ssafsound/domain/post/service/PostService.java
src/test/java/com/ssafy/ssafsound/domain/board/controller/BoardControllerTest.java
src/test/java/com/ssafy/ssafsound/domain/board/service/BoardServiceTest.java
src/test/java/com/ssafy/ssafsound/domain/post/service/PostServiceTest.java
src/test/java/com/ssafy/ssafsound/global/util/fixture/BoardFixture.java
src/test/java/com/ssafy/ssafsound/global/util/fixture/PostFixture.java

- #169 
- 게시글 쓰기 단위 테스트 코드 구현
- 게시판 조회 쿼리문 수정(usedBoard가 false면 조회되지 않도록)

test: 게시글 쓰기 단위 테스트 코드 구현

---

src/main/java/com/ssafy/ssafsound/domain/post/controller/PostController.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostReqDto.java

fix: 페이지네이션 cursor 버그 수정

---

src/main/java/com/ssafy/ssafsound/domain/comment/dto/GetCommentResDto.java

- #268 
- 대댓글이 있는 댓글 삭제 시 오류 해결

fix: 댓글 조회 버그 수정

---

build.gradle
src/main/java/com/ssafy/ssafsound/domain/member/controller/MemberController.java
src/main/java/com/ssafy/ssafsound/domain/member/dto/PostMemberInfoReqDto.java
src/main/java/com/ssafy/ssafsound/domain/member/exception/MemberErrorInfo.java
src/main/java/com/ssafy/ssafsound/domain/member/service/MemberService.java
src/main/java/com/ssafy/ssafsound/domain/term/controller/TermController.java
src/main/java/com/ssafy/ssafsound/domain/term/domain/MemberTermAgreement.java
src/main/java/com/ssafy/ssafsound/domain/term/domain/Term.java
src/main/java/com/ssafy/ssafsound/domain/term/domain/TermElement.java
src/main/java/com/ssafy/ssafsound/domain/term/dto/GetTermsResDto.java
src/main/java/com/ssafy/ssafsound/domain/term/repository/MemberTermAgreementRepository.java
src/main/java/com/ssafy/ssafsound/domain/term/repository/TermRepository.java
src/main/java/com/ssafy/ssafsound/domain/term/service/TermService.java
src/test/java/com/ssafy/ssafsound/domain/member/controller/MemberControllerTest.java
src/test/java/com/ssafy/ssafsound/domain/member/service/MemberServiceTest.java
src/test/java/com/ssafy/ssafsound/global/util/fixture/MemberFixture.java
src/test/java/com/ssafy/ssafsound/global/util/fixture/TermFixture.java

- #271 
- 약관 조회 API 호출 시, usedYN 즉 사용중인 약관들의 List를 Response로 제공합니다.
- 회원가입 이후, 정보 입력을 할 때, 동의한 약관 Id들에 대한 Request Body에 필드값을 추가로 넣었습니다.
- 사용중인 필수 약관 동의들의 Id들이 Request Body로 넘어오지 않으면 예외가 발생합니다. (즉, 회원정보를 입력할 수 없음)
- 테스트 코드 및 Rest Docs를 수정했습니다.

feat: 멤버 회원가입 시, 필수 약관 비즈니스 로직 추가

---

src/main/java/com/ssafy/ssafsound/domain/auth/controller/AuthController.java
src/main/java/com/ssafy/ssafsound/domain/member/controller/MemberController.java
src/main/java/com/ssafy/ssafsound/domain/member/repository/MemberRepository.java
src/main/java/com/ssafy/ssafsound/domain/member/service/MemberService.java
src/test/java/com/ssafy/ssafsound/domain/member/service/MemberServiceTest.java
src/test/java/com/ssafy/ssafsound/global/util/fixture/MemberFixture.java

- #277 
- 회원 탈퇴 시, 쿠키 삭제 로직을 추가했습니다.
- 매개변수의 memberId만 필요한경우, 코드 리팩토링 및 테스트 코드를 수정했습니다.
- callback API 호출 시, member의 존재 유무에 따른 비즈니스 로직을 Indent Depth를 줄이기 위해 리팩토링 했습니다.

refactor: 회원 탈퇴 시, 쿠키 삭제 및 비즈니스 로직 리팩토링

---

src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitDynamicQueryRepositoryImpl.java

- #285
- 리크루트 마감 여부가 true인 경우, 전체 엔티티가 조회되도록 동적 쿼리 수정

fix: 리크루트 마감 여부 false인 경우만 적용되도록 동적 쿼리 수정

---

src/main/java/com/ssafy/ssafsound/domain/recruit/event/RecruitEventListener.java
src/main/java/com/ssafy/ssafsound/domain/recruit/repository/RecruitRepository.java
src/main/java/com/ssafy/ssafsound/domain/recruitapplication/repository/RecruitApplicationRepository.java

- #287
- 회원 탈퇴시, 다른 회원들이 리크루트 사용에 지장이없도록 탈퇴유저가 작성한 리크루트 글 soft delete처리 및 리크루트 신청 일괄 취소

feat: 회원 탈퇴시 리크루트 일괄 삭제 및 리크루트 신청 일괄 취소

---

src/main/java/com/ssafy/ssafsound/domain/recruit/service/RecruitService.java

- 리크루트 업데이트 시, 리크루트 제한 사항 미반영으로 인한 업데이트 쿼리 추가 
- Cascade persist 대신 별도의 update 쿼리 사용

fix: recruit 업데이트시, limitation값 반영되지 않는 오류 수정

---

src/main/java/com/ssafy/ssafsound/domain/auth/controller/AuthController.java
src/main/java/com/ssafy/ssafsound/domain/auth/service/AuthService.java

- #296 
- 어떠한 이유로도 로그아웃 API 요청이 왔을때, 쿠키가 삭제되도록 리팩토링했습니다.
- 현재 .ssafsound.com domain 설정으로 인해 test.ssafsound.com 및 ssafsound.com 으로 oauth login을 진행했을때 브라우저에 쿠키가 생성됩니다.
- 로그아웃 로직에서 토큰 값에 대한 검증 후, memberId를 추출하여 memberToken을 삭제하는 로직이 존재했습니다. memberId가 테스트 서버 및 실 서버에서 체크됨에 따라 존재하지 않아 서버 에러가 발생하는 원인이 있었습니다.
- MemberToken은 One To One 관계임으로 최초 생성 후, 업데이트만 진행될 수 있게 위에서 언급한 삭제 로직을 제거했습니다.

refactor: 멤버의 로그아웃 로직 리팩토링

---

src/docs/asciidoc/comment.adoc
src/docs/asciidoc/post.adoc
src/main/java/com/ssafy/ssafsound/domain/board/repository/BoardRepository.java
src/main/java/com/ssafy/ssafsound/domain/post/controller/PostController.java
src/main/java/com/ssafy/ssafsound/domain/post/dto/GetPostAllSearchOffsetReqDto.java
src/main/java/com/ssafy/ssafsound/domain/post/repository/PostRepository.java
src/main/java/com/ssafy/ssafsound/domain/post/service/PostService.java
src/main/resources/static/docs/index.html
src/test/java/com/ssafy/ssafsound/domain/post/controller/PostControllerTest.java
src/test/java/com/ssafy/ssafsound/domain/post/service/PostServiceTest.java
src/test/java/com/ssafy/ssafsound/global/util/fixture/PostFixture.java

- #316 
- 전체 게시글 검색 기능 구현
- 게시글 목록 조회에 삭제되거나 없는 boardId가 주어질때 예외가 발생하도록 수정
- API 문서 최신화

feat: 전체 게시글 검색 기능 구현
